#!/bin/bash
# Stax build script template
# Generated by: stax build:generate

set -e

echo "Running build scripts..."

script_folder="scripts/build"

# Check if the script subfolder exists
if [ -d "$script_folder" ]; then
    # Loop through each script file in the subfolder
    for script_file in "$script_folder"/*.sh; do
        # Check if the file is a regular file
        if [ -f "$script_file" ]; then
            echo ""
            echo "Executing: $(basename "$script_file")"
            # Run the script file
            bash "$script_file"
        fi
    done
else
    echo "Error: $script_folder does not exist"
    exit 1
fi

echo ""
echo "Build complete!"
