package ddev

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"text/template"
)

const nginxMediaProxyTemplate = `# Remote media proxy configuration
# This allows loading media from {{.CDNName}} without local storage
# Generated by Stax

location ~ ^/wp-content/uploads/(.*)$ {
    # Try local file first
    try_files $uri @proxy_media;
}

location @proxy_media {
    # Try primary CDN first
    proxy_pass {{.CDNURL}}$request_uri;
    proxy_intercept_errors on;
    proxy_ssl_server_name on;
    proxy_ssl_verify off;

    # Fallback to WPEngine if CDN fails
    error_page 404 = @wpengine_fallback;

    {{if .CacheEnabled}}
    # Caching configuration
    proxy_cache media_cache;
    proxy_cache_valid 200 {{.CacheTTL}};
    proxy_cache_valid 404 1m;
    proxy_cache_key "$scheme$request_method$host$request_uri";

    # Cache headers
    expires {{.CacheTTL}};
    add_header Cache-Control "public, immutable";
    add_header X-Cache-Status $upstream_cache_status;
    {{end}}
    add_header X-Proxy-Source "cdn";

    # Proxy headers
    {{range $key, $value := .ProxyHeaders}}
    proxy_set_header {{$key}} {{$value}};
    {{end}}

    # Hide upstream headers
    proxy_hide_header Set-Cookie;
    proxy_ignore_headers Set-Cookie;
}

location @wpengine_fallback {
    proxy_pass {{.WPEngineURL}}$request_uri;
    proxy_ssl_server_name on;
    proxy_ssl_verify off;

    {{if .CacheEnabled}}
    # Caching
    proxy_cache media_cache;
    proxy_cache_valid 200 {{.CacheTTL}};
    proxy_cache_key "$scheme$request_method$host$request_uri";
    expires {{.CacheTTL}};
    {{end}}
    add_header X-Proxy-Source "wpengine";

    # Proxy headers
    {{if .WPEngineHost}}
    proxy_set_header Host {{.WPEngineHost}};
    {{end}}
    proxy_hide_header Set-Cookie;
    proxy_ignore_headers Set-Cookie;
}

{{if .CacheEnabled}}
# Cache path configuration
# This is configured at the server level
# proxy_cache_path /var/cache/nginx/media
#     levels=1:2
#     keys_zone=media_cache:10m
#     max_size={{.CacheMaxSize}}
#     inactive={{.CacheTTL}};
{{end}}
`

const nginxCacheConfigTemplate = `# Nginx cache configuration for media proxy
# Add this to your nginx_full/nginx-site.conf or similar

proxy_cache_path /var/cache/nginx/media
    levels=1:2
    keys_zone=media_cache:10m
    max_size={{.CacheMaxSize}}
    inactive={{.CacheTTL}};
`

// GenerateMediaProxyConfig creates Nginx configuration for remote media proxying
func GenerateMediaProxyConfig(projectPath string, options MediaProxyOptions) error {
	if !options.Enabled {
		return nil
	}

	// Set defaults
	if options.CacheTTL == "" {
		options.CacheTTL = "30d"
	}
	if options.CacheMaxSize == "" {
		options.CacheMaxSize = "10g"
	}
	if options.CDNName == "" {
		options.CDNName = "CDN"
	}

	// Default proxy headers
	if options.ProxyHeaders == nil {
		options.ProxyHeaders = map[string]string{
			"X-Real-IP":       "$remote_addr",
			"X-Forwarded-For": "$proxy_add_x_forwarded_for",
		}
	}

	// Create .ddev/nginx_full directory
	nginxDir := filepath.Join(projectPath, ".ddev", "nginx_full")
	if err := os.MkdirAll(nginxDir, 0755); err != nil {
		return fmt.Errorf("failed to create nginx_full directory: %w", err)
	}

	// Parse and execute template
	tmpl, err := template.New("media-proxy").Parse(nginxMediaProxyTemplate)
	if err != nil {
		return fmt.Errorf("failed to parse template: %w", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, options); err != nil {
		return fmt.Errorf("failed to execute template: %w", err)
	}

	// Write to file
	configPath := filepath.Join(nginxDir, "media-proxy.conf")
	if err := os.WriteFile(configPath, buf.Bytes(), 0644); err != nil {
		return fmt.Errorf("failed to write nginx config: %w", err)
	}

	// Also generate cache configuration separately
	if options.CacheEnabled {
		if err := generateCacheConfig(nginxDir, options); err != nil {
			return err
		}
	}

	return nil
}

// generateCacheConfig creates a separate cache configuration file
func generateCacheConfig(nginxDir string, options MediaProxyOptions) error {
	tmpl, err := template.New("cache-config").Parse(nginxCacheConfigTemplate)
	if err != nil {
		return fmt.Errorf("failed to parse cache template: %w", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, options); err != nil {
		return fmt.Errorf("failed to execute cache template: %w", err)
	}

	cachePath := filepath.Join(nginxDir, "cache-config.conf")
	if err := os.WriteFile(cachePath, buf.Bytes(), 0644); err != nil {
		return fmt.Errorf("failed to write cache config: %w", err)
	}

	return nil
}

// WriteNginxConfig writes a custom Nginx configuration to the DDEV project
func WriteNginxConfig(projectPath, filename, content string) error {
	nginxDir := filepath.Join(projectPath, ".ddev", "nginx_full")
	if err := os.MkdirAll(nginxDir, 0755); err != nil {
		return fmt.Errorf("failed to create nginx_full directory: %w", err)
	}

	configPath := filepath.Join(nginxDir, filename)
	if err := os.WriteFile(configPath, []byte(content), 0644); err != nil {
		return fmt.Errorf("failed to write nginx config: %w", err)
	}

	return nil
}

// ReadNginxConfig reads a Nginx configuration file from the DDEV project
func ReadNginxConfig(projectPath, filename string) (string, error) {
	configPath := filepath.Join(projectPath, ".ddev", "nginx_full", filename)
	data, err := os.ReadFile(configPath)
	if err != nil {
		return "", fmt.Errorf("failed to read nginx config: %w", err)
	}
	return string(data), nil
}

// ValidateNginxConfig validates Nginx configuration syntax using DDEV
func ValidateNginxConfig(projectPath string) error {
	mgr := NewManager(projectPath)

	// Execute nginx -t in the container
	err := mgr.Exec([]string{"nginx", "-t"}, &ExecOptions{
		Service: "web",
	})

	if err != nil {
		return fmt.Errorf("nginx configuration is invalid: %w", err)
	}

	return nil
}

// GetDefaultMediaProxyOptions returns default media proxy options
func GetDefaultMediaProxyOptions() MediaProxyOptions {
	return MediaProxyOptions{
		Enabled:      true,
		CDNName:      "BunnyCDN",
		CacheTTL:     "30d",
		CacheMaxSize: "10g",
		CacheEnabled: true,
		ProxyHeaders: map[string]string{
			"X-Real-IP":       "$remote_addr",
			"X-Forwarded-For": "$proxy_add_x_forwarded_for",
		},
	}
}
